var list = [
    {val:"1", txt:"1 Alfa"},
    {val:"2", txt:"2 Bravo"},
    {val:"3", txt:"3 Charlie"},
    {val:"4", txt:"4 Delta"},
    {val:"5", txt:"5 Echo"},
    {val:"6", txt:"6 Foxtrot"},
    {val:"7", txt:"7 Golf"},
    {val:"8", txt:"8 Hotel"},
    {val:"9", txt:"9 India"},
    {val:"10", txt:"10 India"},
    {val:"11", txt:"11 Alfa"},
    {val:"12", txt:"12 Bravo"},
    {val:"13", txt:"13 Charlie"},
    {val:"14", txt:"14 Delta"},
    {val:"15", txt:"15 Echo"},
    {val:"16", txt:"16 Foxtrot"},
    {val:"17", txt:"17 Golf"},
    {val:"18", txt:"18 Hotel"},
    {val:"19", txt:"19 India"},
];
